version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: hypnosis-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: hypnosis
      POSTGRES_PASSWORD: hypnosis_password
      POSTGRES_DB: hypnosis_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hypnosis"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application
  app:
    image: ghcr.io/phonkd/flowtime:sha-fb0e0a3
    container_name: hypnosis-app
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
    environment:
      NODE_ENV: development
      PORT: 5000
      SESSION_SECRET: your_secure_session_secret_key_here
      USE_DATABASE: true
      DATABASE_URL: postgresql://hypnosis:hypnosis_password@postgres:5432/hypnosis_db
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
