FROM postgres:14-alpine

# Copy our initialization script
COPY init-db.sh /docker-entrypoint-initdb.d/

# Make sure the script is executable
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# The default command for the postgres image will run the script automatically